# setup
title:       TodoXChile
tagline:     'Somos organizaciones de la sociedad civil que trabajan en emergencia, pobreza, infancia, educación, medioambiente, vivienda, voluntariado, cooperación internacional, salud, capacitación, género, DD.HH. y en diversas otras temáticas, que, dejando de lado nuestras agendas, hemos armado una inédita mesa de coordinación nacional de ayuda frente a la catástrofe del norte de Chile.<br/><br/> Estamos en directa coordinación con la ONEMI, el gobierno regional y el Ministerio de Desarrollo Social.'
edition:     '' #'#FuerzaNorte'
description: 'Herramienta de unificación de los esfuerzos de voluntarios y sociedad civil organizada para llegar con la ayuda de manera eficiente.'
baseurl:     'http://www.todoxchile.cl' #example: 'http://www.todoxchile.cl' OR '/todoxchile'
basedomain:  'todoxchile.cl' #example: 'todoxchile.cl' OR 'ciudadanointeligente.github.io'
analytics:   'UA-41822715-5'
twitter:     '@ciudadanoi'
twitter_txt: 'Soy parte y hacemos #TodoXChile'
hashtag:     'TodoXChile'
disqus:      'todoxchile'
slide01:     '//farm8.staticflickr.com/7666/16904241940_01b43bc8dc_k.jpg'
slide02:     '//farm8.staticflickr.com/7592/16930454277_a4cb51d648_k_d.jpg'
slide03:     '//farm8.staticflickr.com/7612/16469247234_7740da0b78_h_d.jpg'

# credits
author:
  name:      Fundación Ciudadano Inteligente
  email:     prensa@ciudadanointeligente.org

# dependencies
markdown:    redcarpet
highlighter: pygments

# permalinks
# use of `relative_permalinks` ensures post links from the index work properly.
relative_permalinks: true

collections:
  partners:
    output: true