# setup
title:       Todo X Chile
tagline:     'Unificando los esfuerzos para llegar con la ayuda de manera eficiente'
description: 'Herramienta de unificación de los esfuerzos de voluntarios y sociedad civil organizada para llegar con la ayuda de manera eficiente.'
baseurl:     '/todoxchile' #example: 'http://www.todoxchile.cl'
basedomain:  'ciudadanointeligente.github.io' #example: 'todoxchile.cl'
analytics:   'UA-31247996-1'

# social
twitter: '@ciudadanoi'
hashtag: '#FuerzaChile'

# credits
author:
  name:      Fundación Ciudadano Inteligente
  email:     prensa@ciudadanointeligente.org

# dependencies
markdown:    redcarpet
highlighter: pygments

# permalinks
# use of `relative_permalinks` ensures post links from the index work properly.
relative_permalinks: true

collections:
  partners:
    output: true